### ISSUE TITLE
`os.chdir` fails when script invoked as `python x` rather than `./x`

### ISSUE THREAD

**Issue by Fing086** [jerbzz/pi-eco-indicator#20]
Hi,

Firstly, great software and instructions !

I am running a Pi Zero with Inky pHat
Along with 32bit Buster with no desktop

I have only followed your instructions and not installed anything else.

After about 24 hours of usage I notice that the graphics for the graph start to not show from right to left as the day goes on?

Also if I restart the Pi, the graph doesnt come back, as though it remembers that it wasnt there!

I have fully reinstalled the system and started from scratch but the same has happened again.

Any idea on what could be wrong?

Thanks in advance

**Comment by jerbzz** [comment]
Hello. It sounds very much like your installation isn't updating its database, for whatever reason.

Please could you show me the output of `./store_data.py` and `crontab -l` ?

**Comment by Fing086** [comment]
I left it going all day today and then at some point the graph returned and has been there ever since with no issues.

crontab -l gives me:

'@reboot /bin/sleep 30; /usr/bin/python3 /home/pi/pi-eco-indicator/store_data.py > /home/pi/pi-eco-indicator/eco_indicator.log 2>&1
@reboot /bin/sleep 40; /usr/bin/python3 /home/pi/pi-eco-indicator/update_display.py > /home/pi/pi-eco-indicator/eco_indicator.log 2>&1
*/30 * * * * /bin/sleep 5; /usr/bin/python3 /home/pi/pi-eco-indicator/update_display.py > /home/pi/pi-eco-indicator/eco_indicator.log 2>&1
57 16 * * * /usr/bin/python3 /home/pi/pi-eco-indicator/store_data.py > /home/pi/pi-eco-indicator/eco_indicator.log 2>&1
57 18 * * * /usr/bin/python3 /home/pi/pi-eco-indicator/store_data.py > /home/pi/pi-eco-indicator/eco_indicator.log 2>&1
57 20 * * * /usr/bin/python3 /home/pi/pi-eco-indicator/store_data.py > /home/pi/pi-eco-indicator/eco_indicator.log 2>&1'

Also just tried to run store_data.py manually to export output to a text file and I got the following in terminal:

'Traceback (most recent call last):
  File "/home/pi/pi-eco-indicator/store_data.py", line 215, in <module>
    os.chdir(os.path.dirname(sys.argv[0]))
FileNotFoundError: [Errno 2] No such file or directory: '''


However when I reboot the pi, it auto runs and runs fine :)
Hope that all helps in some way

**Comment by jerbzz** [comment]
You need the backtick, the one to the left of the number 1 key, below Esc :) I've edited your post to fix that.

OK so we definitely have an error when running `store_data.py`... 

Can you show me the entire sequence - the command you run as well as the output?

**Comment by Fing086** [comment]
To get the error I just cd to the dir and type √python store_data.py√
I cant show any output as all I get is the error.

I SSH from Mac terminal as well if that changes anything.

**Comment by jerbzz** [comment]
Ah, I see! I (and the instructions) invoke it via `./store_data.py` as the script is marked as executable.

However it is entirely legit to invoke it as `python store_data.py`. Can you edit `store_data.py` for me, changing line 215 from

`os.chdir(os.path.dirname(sys.argv[0]))`

to `os.chdir(sys.path[0])`

and see if that fixes your issue? :)

**Comment by Fing086** [comment]
Ah, I was only running through python to export (`>>`) to the text file.
However, ive just tried it again and now get

`Inky pHAT display selected.
Working in Octopus Agile import mode.
Agile version set: £1 cap, new-new formula (current)
Selected region G
Connected to database...
API request successful, status 200.
100 prices were inserted, ending at 22:00 on Saturday 17 Jun.
1 unneeded data points from the past were deleted.`

As said earlier, it does seem to be working now so not sure why the graph messed up previously.

I assume that even with this change, the crontab script will auto run the software when needed?

**Comment by Fing086** [comment]
Hmm, why do you need to export to a text file? Is that a useful feature for you?
**_Its just the way I have always grabbed output!_**

Tried it again with or without python?
**_Tried it with both and seems fine_**

Did you have a go at implementing my change? I'm testing it here to check it doesn't mess with the cron job, but I don't see any reason why it would.
**_Yes, and so far all seems great, the pi is resetting every 30 mins_**



The graph didn't mess up, it ran out of data, because store_data.py was failing. If the time at the top of the screen is correct (well, correct for the last 30 mins) then update_display.py is working fine. It's designed to be tolerant of missing data so it'll just display less and less until it runs out. Perhaps I should add a message on there that says "oops, no data!"

_**Possibly a good idea that as will stop it looking 'broken' and rather like its trying but not finding the data it needs.**_


(triple backticks on the lines above and below your paste snippet will preserve the line breaks!)
**_As you have probably guessed, quite new to all this GitHub stuff, but thankful for people like yourself who post on here with some great programs :)_**

**Comment by jerbzz** [comment]
Interesting, I just copy and paste straight from the terminal! Sounds like we have a fix for at least a partial issue, so I'll implement that now... do you fancy having a go at a "no data" message? 🤔

**Comment by Fing086** [comment]
Ill try and get the time to have a look, always difficult looking at someone elses code but ill certainly see what I can do :)

**Comment by jerbzz** [comment]
Fixed in https://github.com/jerbzz/pi-eco-indicator/commit/5335f1dd2d662f7257050b7cd1c922986ee14c56
